# General config file example

# Camera parameters
device: 0 # 'C:\Users\Ivan\scene_1_merged_1.mp4' # 
resolution: [1024, 768]
fps: 10
angle: -20
height: -3
focal_length: 2.2

clahe_limit: 3  # Pre-processing parameters - CLAHE contrast adjustment
clahe_grid_sz: [8, 8]

weights: "C:\\Users\\Ivan\\Repositories\\capturing_c\\lr_weights.yaml"

bs_history: 50
var_thr: 16
shadows: True
dilate_it: 1
m_op_it: 1

# Cascade filtering speeds up detection through filtering unlikely objects. Set value to zero to disable filtering.
cont_area_thr: 0.001  # Chosen 0.0005 Minimal object cnt area to be considered: object cnt area / RES[0] * RES[1] > cont_area_thr
extent_thr: 0.2
max_distance: 25 # Ignore objects which have distance more than MAX_DISTANCE: obj distance > MAX_DISTANCE.
margin: 0  # Ignore objects intersecting frame margin: left img border + MARGIN < obj coordinates < right img border - MARGIN